version: "3.7"

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_daemon
    ports:
      - "4001:4001" # Swarm
      - "5001:5001" # API
      - "8080:8080" # Gateway
    volumes:
      - ./ipfs-data:/data/ipfs
    restart: always
    command: "daemon --migrate=true"

volumes:
  ipfs-data:
